### ISSUE TITLE
Artix Sway

### ISSUE THREAD

**Issue by BPOH** [MuratovAS/dotfiles#2]
Здравствуй, очень здоровский конфиг для Artix sway, было бы очень здорово еслиб он вобрал в себя всё самое лучшее cli/tui  от manjaro sway

**Comment by MuratovAS** [comment]
Добрый день, спасибо.
Можете конкретизировать, что бы вы хотели унаследовать из `manjaro sway`?

**Comment by BPOH** [comment]
Там всё отлично! кроме того что это manjaro) против ничего не имею но посли artix оно какоето всё грамоздкое... В manjaro всё шикарно от мэнеджера входа до всего остального cli wifi bluetootch менеджер блютуза также консольный не текстовый а консольный cli уведомления так и не понял что это их делает, регулировка звука подсветки, также всплывает какаято неведомая но так гармоничная штука... иконки программ рабочих столов календарь calcurse ночной режим, вроде всё. ОФтопный вопрос, прости пожалуйста, может сможешь подсказать сейчас пробую EndeavourOS до этого пару дней назад ставил manjaro до этого пару лет использовал artix недавно ноут обновил там процессор со встроенной графикой 12th Gen Intel i7-12700H Intel Alder Lake-P 
тут стоят пакеты
~ » sudo pacman -Q| grep intel                                   user@pc
[sudo] пароль для user: 
intel-ucode 20230613-1
lib32-vulkan-intel 23.1.3-1
vulkan-intel 23.1.3-1
и графика в играх работает очень хорошо, ставлю Artix все драйвера как советует арчь вики intel-media-driver и она не работает может ли быть это связанно с отсутствием systemD? но это же чепуха... всё это в portprotone тестировал в artix disciples II который пень первый тянул с видеокартой 1 мегабвйт разогревает этот комп до 70 градусов :D извени пожалуйста за офтоп, но если подскажешь как настраивается правильно видеокарта в Artix я прям буду счастлив! в манджаро к стати тоже все работает хорошо( но мне так нравится artix, но у меня такие кривые руки

**Comment by MuratovAS** [comment]
Как вы уже отметили, большинство дистрибутивов "громоздкие". 
Я бы НЕ хотел что бы мой стал таковым, сейчас иду путем минимизации количества компонентов. 
Немного о решениях:
- Bluetooth manager, только что сделал переход на TUI вариант (коммит уже в репозитории). 
- Login manager, не вижу в нем смысла, обычно пользователь один (тот что собрал это чудо))), да еще и не требующий авторизации. Авторизация это ввод пароля расшифровки диска.
- Уведомление об изменение звука или подсветки, не вижу в них смысла, эта информация есть в waybar.
- Все остальное присутствует в моём гайде ака. сборки
